### ISSUE TITLE
로그인시 아이디와 패스워드 DB 연동

### ISSUE THREAD

**Issue by nayeon0891** [team3-syu/DB-Project#10]
## 📝작업 내용

> 로그인시 고객 아이디와 패스워드가 일치하면 로그인 될 수있게 DB와 연동해서 코드 작성했습니다.

## 💬리뷰 요구사항(선택)

> 문제 발견시 알려주시면 감사하겠습니다.
>

**Comment by Yoon0917** [comment]
확인했습니다 앞으로는 push전 꼭 issue 날려주세요
