### ISSUE TITLE
약 성분 crud작성

### ISSUE THREAD

**Issue by syongsyong6035** [team3-syu/DB-Project#11]
## #️⃣연관된 이슈

> ex) #이슈번호, #이슈번호

## 📝작업 내용
약 성분 구조에 대해 작성하였습니다
crud구조 
domain 계층
-ingredientDTO 데이터 표현하는 객체들
repository 계층
-ingredient-mapper.xml xml매퍼 파일이 위치한다

DAO계층
-ingredientDAO  실제 DB와 연동하는 코드

Service 계층 
-ingredientService 비즈니스 로직을 처리하는 코드

Contoller 계층
-ingredientContrller 요청받아 처리하고 처리결과를 반환하는 역할을 한다

Application 계층 
- 사용자 인터테이스 연동하여 사용자 입력받고 출력한다

성분을 읽고 추가하고 삽입하고 수정하는 코드를 작성하였다

## 💬리뷰 요구사항(선택)

혹시 부족한거나 작동 안되는거 있으면 알려주세요

**Comment by Yoon0917** [comment]
상위단계 확인으로 인한 close합니다.
