### ISSUE TITLE
#17 메인Application과 Member/Application 분리 And Member/Application -> Member/Member로 클래스 이름변경

### ISSUE THREAD

**Issue by Yoon0917** [team3-syu/DB-Project#17]
## #️⃣연관된 이슈
# #10 

## 📝요구사항
테스트를 완료 하셨다면 프로그램의 중앙기능을 담당하는 루트 Application기능과 member/Application기능을 나눠주세요
ex) 회원가입시 루트Application에서 member/application 의 회원가입 메서드를 호출할때 member/application 함수에서 실행
즉 프로그램 전체에서 동작하는 main() 메서드는 루트Application 클래스 하나뿐입니다.

다른분들도 main()함수로 테스트를 완료 하였다면 Application 클래스의 이름을 각자 맡은 테이블 이름으로 변경해주세요
>

**Comment by inredzero** [comment]
넵 변경 했고 PR보내겠습니다!

**Comment by nayeon0891** [comment]
넵 변경 완료했습니다
