### ISSUE TITLE
#연관된 이슈 없음

### ISSUE THREAD

**Issue by Yoon0917** [team3-syu/DB-Project#18]
## 💬리뷰 요구사항(선택)
- 각자테이블의 데모 데이터를 삽입하는 쿼리문을 각 branch에 푸쉬 해주세요 파일경로는 sqlfolder/ 입니다

**Comment by Yoon0917** [comment]
확인했으면 코멘트 부탁드립니다.

**Comment by nayeon0891** [comment]
sql폴더에 쿼리문 올렸습니다.
