### ISSUE TITLE
medicine 검색 기능 및 검색 오류 수정  ++ sql insert data 추가

### ISSUE THREAD

**Issue by inredzero** [team3-syu/DB-Project#20]
## 📝작업 내용
> medicine 검색 기능을 전반적으로 구현 했습니다.
> 부작용 검색할때 검색이 안되는 오류가 있어 MedicineDAO 코드 수정했습니다.
> sql insert 내용 넣어놨습니다 (오늘까지 data 더 추가 하겠습니다,)

## 💬리뷰 요구사항
> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요
> 먼저 local db에 제가 작성한 sql파일 넣어 테이블이랑 데이터 넣어주세요.
>  통합할 Application에서 잘 실행이 되는지
>  실행 후 CRUD 랑 검색 기능 정상 작동 되는지.

변경할 사항이나 추가적으로 해야될게 있으면 말씀해주세요!!!

**Comment by Yoon0917** [comment]
pr까지 수락했습니다 고생하셨습니다
