### ISSUE TITLE
약 성분 컬럼 추가 및 오류 수정 crud수정

### ISSUE THREAD

**Issue by syongsyong6035** [team3-syu/DB-Project#22]
## 📝작업 내용

SQL문
ALTER TABLE ingredients ADD COLUMN Component VARCHAR(255);
crud 수정 하였습니다 
component로 약 성분 컬럼 추가하였습니다 
그리고 동일한 코드 번호 가 있을시 삭제할때 나오는 오류 수정 하였습니다

## 💬리뷰 요구사항(선택)

> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요

**Comment by Yoon0917** [comment]
고생 하셨습니다. #26도 확인해주세요
