### ISSUE TITLE
약 성분  이름,효과,부작용,성분 SQL문

### ISSUE THREAD

**Issue by syongsyong6035** [team3-syu/DB-Project#24]
## 📝작업 내용
INSERT INTO Ingredients (IngredientCode, IngredientName, Effect, SideEffect, Component)
VALUES
(1, '타이레놀', '해열, 진통', '장기 복용 시 간 손상 위험, 알레르기 반응', '아세트아미노펜'),
(2, '부루펜', '해열, 진통, 소염', '위장 자극, 출혈 위험, 신장 손상 위험', '이부프로펜'),
(3, '겔포스', '인후통 완화', '알레르기 반응, 국소 마취 효과', '리도카인, 벤조카인 등'),
(4, '베나치오', '소화불량, 위산 과다, 속쓰림 완화', '두통, 어지러움, 변비 또는 설사', '라니티딘, 옴에프라졸 등'),
(5, '판콜', '감기 증상 완화, 해열, 진통', '졸음, 구토, 위장 불편감', '아세트아미노펜과 다른 감기약 성분들'),
(6, '후시딘', '항균 작용', '위장 불편감, 발진, 가려움증', '푸시드산'),
(7, '마데카솔', '상처 치유 촉진, 피부 재생', '발진, 가려움증, 접촉성 피부염', '센텔라 아시아티카 추출물'),
(8, '페니라민', '항히스타민 작용, 알레르기 증상 완화', '졸음, 구강 건조, 시야 흐림', '페니라민'),
(9, '임팩타민', '에너지 대사 촉진, 피로 회복', '일반적으로 안전하나 과다 복용 시 소화기 증상 가능', '비타민 B군, 비타민 C 등'),
(10, '가스모틴', '위장 운동 촉진, 소화불량 완화', '설사, 복통, 두통', '모사프리드'),
(11, '이가탄', '구강 내 염증 및 인후통 완화', '미각 변화, 구강 자극, 치아 착색', '클로르헥시딘, 벤자미딘 등'),
(12, '로테라', '간 보호, 간 기능 개선', '일반적으로 안전하나 드물게 소화기 증상 가능', '실리마린'),
(13, '아로나민', '에너지 대사 촉진, 신경계 기능 유지', '일반적으로 안전하나 과다 복용 시 소화기 증상 가능', '비타민 B1, 비타민 B2, 비타민 B6, 비타민 B12, 비타민 C'),
(14, '비판텐', '피부 재생 촉진, 상처 치유 촉진', '매우 드물게 알레르기 반응 가능', '덱스판테놀'),
(15, '레보티라세탐', '항경련 작용', '졸음, 어지러움, 두통, 행동 변화', '레베티라세탐'),
(16, '모티리움', '소화기계 운동 촉진, 구토 억제', '두통, 졸음, 불규칙한 심장박동 (드물게)', '돔페리돈'),
(17, '알레그라', '항히스타민 작용, 알레르기 증상 완화', '두통, 졸음, 구강 건조', '펙소페나딘'),
(18, '트리메부틴', '위장관 운동 조절, 복통 및 소화불량 완화', '변비, 구토, 발진 (드물게)', '트리메부틴'),
(19, '콜대원', '감기 증상 완화, 해열, 진통', '졸음, 구강 건조, 시야 흐림, 변비', '아세트아미노펜, 클로르페니라민, 페닐에프린 등'),
(20, '엑세라민', '콜라겐 생성 촉진, 면역력 향상', '일반적으로 안전하나 과다 복용 시 소화기 증상 가능', '비타민 C (아세스코르빈산)'),
(21, '니코틴패치', '금연 보조제, 니코틴 금단 증상 완화', '피부 자극, 불면증, 두통', '니코틴'),
(22, '프로바이오틱스', '장내 균총 개선, 면역력 향상', '매우 드물게 소화기 증상 가능', '다양한 유산균 종 (Lactobacillus, Bifidobacterium 등)'),
(23, '머시론', '기침 억제, 가래 배출 촉진', '졸음, 구역, 구토', '구아이페네신, 덱스트로메토르판 등'),
(24, '스토가', '멀미, 구토 완화', '졸음, 구강 건조, 시야 흐림', '디멘히드리네이트, 메클리진 등'),
(25, '락토핏', '장내 균총 개선, 면역력 향상', '매우 드물게 소화기 증상 가능', '다양한 유산균 종 (Lactobacillus, Bifidobacterium 등)'),
(26, '케토톱', '소염, 진통', '위장 자극, 출혈 위험, 신장 손상 위험', '케토프로펜'),
(27, '후라시딘', '항균 작용', '위장 불편감, 발진, 가려움증', '푸시드산'),
(28, '아세트아미노펜', '해열, 진통', '장기 복용 시 간 손상 위험, 알레르기 반응', '아세트아미노펜'),
(29, '테라플루', '감기 증상 완화, 해열, 진통', '졸음, 구강 건조, 시야 흐림, 변비', '아세트아미노펜, 페닐에프린 HCI, 클로르페니라민 말레이트 등');

## 💬리뷰 요구사항(선택)

> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요

**Comment by Yoon0917** [comment]
sql folder에 .sql파일로 작성해서 push 해주세요!
++ 제가 확인을 못한거 였네요 ㅠㅠ 죄송합니다.
