### ISSUE TITLE
#26 출력문 한글로 바꿔주세요

### ISSUE THREAD

**Issue by Yoon0917** [team3-syu/DB-Project#26]
## #️⃣연관된 이슈

> #25 

## 📝작업 내용

> 테이블 조회시 제가 한거처럼 한글로 예쁘게 나오게 출력문 수정해주세요 ^^
ex member_id -> 고객 id

## 💬리뷰 요구사항(선택)

> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요
>
> 수정하셨으면 카톡이나 코멘트 부탁드립니다.

**Comment by syongsyong6035** [comment]
네 수정했습니다 확인해주세요!
