### ISSUE TITLE
회원테이블

### ISSUE THREAD

**Issue by nayeon0891** [team3-syu/DB-Project#3]
## 📝작업 내용

CREATE TABLE IF NOT EXISTS member
(
member_code  int primary key NOT NULL auto_increment COMMENT '회원번호',
member_id  VARCHAR(30) NOT NULL COMMENT '아이디',
member_password  VARCHAR(30) NOT NULL COMMENT '비밀번호',
member_name VARCHAR(30) NOT NULL COMMENT '이름',
member_phone  VARCHAR(30) NOT NULL  COMMENT '전화번호',
member_birthday  VARCHAR(30) NOT NULL  COMMENT '생년월일',
member_gender VARCHAR(30) NOT NULL  COMMENT '성별',
member_email  VARCHAR(30) NOT NULL  COMMENT '이메일'
) ENGINE=INNODB;

**Comment by Yoon0917** [comment]
master브랜치 풀 후에 Sqlfolder에 .sql파일로 정리해서 푸쉬해주세요.
