### ISSUE TITLE
성분 테이블 작성

### ISSUE THREAD

**Issue by syongsyong6035** [team3-syu/DB-Project#4]
## 📝작업 내용

CREATE TABLE Ingredients (
    IngredientCode INT PRIMARY KEY, //성분 코드
    IngredientName VARCHAR(255), // 성분이름
    Effect TEXT, //효과
    SideEffects TEXT //부작용
);

## 💬리뷰 요구사항(선택)
혹시 더 필요한 테이블 있으면 알려주세요 !

**Comment by Yoon0917** [comment]
master브랜치 풀 후에 Sqlfolder에 .sql파일로 정리해서 푸쉬해주세요

**Comment by Yoon0917** [comment]
확인했습니다.

**Comment by Yoon0917** [comment]
sql 추가 확인했습니다.
