### ISSUE TITLE
약테이블

### ISSUE THREAD

**Issue by inredzero** [team3-syu/DB-Project#5]
create table medicine
(
	m_code varchar(255) not null primary key,
	m_name varchar(255),
    m_component varchar(255),
	m_effect varchar(255),
	m_side_effect varchar(255),
    m_amount int(255),
    m_strong varchar(10)
);

**Comment by Yoon0917** [comment]
master브랜치 풀 후에 Sqlfolder에 .sql파일로 정리해서 푸쉬해주세요.

**Comment by Yoon0917** [comment]
sql 추가 확인했습니다.
