### ISSUE TITLE
경로 설정이 잘못된거 같습니다

### ISSUE THREAD

**Issue by nayeon0891** [team3-syu/DB-Project#9]
## 📝작업 내용
경로 설정이 안맞는거 같은데 계속 찾아봐도 모르겠습니다...
> 
### 스크린샷 (선택)
![image](https://github.com/team3-syu/DB-Project/assets/132421122/7ab38c07-8ac0-4772-956b-8090c152daf0)

## 💬리뷰 요구사항(선택)

> 해결방법을 코멘트로 작성 부탁드립니다

**Comment by Yoon0917** [comment]
src 하부 경로와 resource  하부경로 대소문자 차이가있었네요 수정하겟습니다.
